<%@ Page Title="" Language="VB" MasterPageFile="~/Admin/adminMaster.master" AutoEventWireup="false" CodeFile="Product.aspx.vb" Inherits="Admin_Product_Product" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

   

    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:OTSProjectConnectionString1 %>" 
        
        SelectCommand="SELECT Product.p_id, Product_img.image_path, Product.p_name, Product.qty, Product.p_price, Brand.b_name, Category.category_name, Subcategory.subcategory_name FROM Product INNER JOIN Product_img ON Product.p_id = Product_img.p_id INNER JOIN Brand ON Product.brand_id = Brand.brand_id INNER JOIN Subcategory ON Product.subcategory_id = Subcategory.subcategory_id INNER JOIN Category ON Subcategory.category_id = Category.category_id" 
        DeleteCommand="DELETE FROM Product FROM Product INNER JOIN Product_img ON Product.p_id = Product_img.p_id WHERE (Product.p_id = @p_id)">
        <DeleteParameters>
            <asp:Parameter Name="p_id" />
        </DeleteParameters>
    </asp:SqlDataSource>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
        CellPadding="10" CellSpacing="10" DataKeyNames="p_id" 
        DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
        <AlternatingRowStyle BackColor="White" />
        <Columns>
            <asp:BoundField DataField="p_id" HeaderText="ID" ReadOnly="True" 
                SortExpression="p_id" />
            <asp:BoundField DataField="p_name" HeaderText="Name" SortExpression="p_name" />
            <asp:ImageField DataImageUrlField="image_path" HeaderText="Image">
                <ControlStyle Height="50px" Width="50px" />
            </asp:ImageField>
            <asp:BoundField DataField="qty" HeaderText="Qty" SortExpression="qty" />
            <asp:BoundField DataField="p_price" HeaderText="Price" 
                SortExpression="p_price" />
            <asp:BoundField DataField="b_name" HeaderText="Brand" SortExpression="b_name" />
            <asp:BoundField DataField="category_name" HeaderText="Category" 
                SortExpression="category_name" />
            <asp:BoundField DataField="subcategory_name" HeaderText="Subcategory" 
                SortExpression="subcategory_name" />
        </Columns>
        
        <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
        <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
        <SortedAscendingCellStyle BackColor="#FDF5AC" />
        <SortedAscendingHeaderStyle BackColor="#4D0000" />
        <SortedDescendingCellStyle BackColor="#FCF6C0" />
        <SortedDescendingHeaderStyle BackColor="#820000" />
    </asp:GridView>
    <asp:Button ID="Button1" class="btn btn-primary" runat="server" Text="Add New Product" PostBackUrl="~/Admin/Product/AddProduct.aspx" />
    <br />

</asp:Content>

