<%@ Page Title="" Language="VB" MasterPageFile="~/Admin/adminMaster.master" AutoEventWireup="false"
    CodeFile="Offers.aspx.vb" Inherits="Admin_Offers" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
        AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="offers_id" DataSourceID="SqlDataSource1"
        ForeColor="#333333" GridLines="None" Width="90%">
        <AlternatingRowStyle BackColor="White" />
        <Columns>
            <asp:BoundField DataField="offers_id" HeaderText="ID" ReadOnly="True" 
                SortExpression="offers_id" />
            <asp:BoundField DataField="offer_desc" HeaderText="Desc" 
                SortExpression="offer_desc" />
            <asp:BoundField DataField="discount" HeaderText="Discount" 
                SortExpression="discount" />
            <asp:BoundField DataField="start_date" DataFormatString="{0:d}" 
                HeaderText="Start Date" SortExpression="start_date" />
            <asp:BoundField DataField="end_date" DataFormatString="{0:d}" 
                HeaderText="End Date" SortExpression="end_date" />
        </Columns>
        <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
        <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
        <SortedAscendingCellStyle BackColor="#FDF5AC" />
        <SortedAscendingHeaderStyle BackColor="#4D0000" />
        <SortedDescendingCellStyle BackColor="#FCF6C0" />
        <SortedDescendingHeaderStyle BackColor="#820000" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:OTSProjectConnectionString1 %>" 
        DeleteCommand="DELETE FROM [Offer] WHERE [offers_id] = @offers_id" 
        InsertCommand="INSERT INTO [Offer] ([offers_id], [offer_desc], [discount], [start_date], [end_date]) VALUES (@offers_id, @offer_desc, @discount, @start_date, @end_date)" 
        SelectCommand="SELECT * FROM [Offer]" 
        UpdateCommand="UPDATE [Offer] SET [offer_desc] = @offer_desc, [discount] = @discount, [start_date] = @start_date, [end_date] = @end_date WHERE [offers_id] = @offers_id">
        <DeleteParameters>
            <asp:Parameter Name="offers_id" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="offers_id" Type="Int32" />
            <asp:Parameter Name="offer_desc" Type="String" />
            <asp:Parameter Name="discount" Type="Int32" />
            <asp:Parameter DbType="Date" Name="start_date" />
            <asp:Parameter DbType="Date" Name="end_date" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="offer_desc" Type="String" />
            <asp:Parameter Name="discount" Type="Int32" />
            <asp:Parameter DbType="Date" Name="start_date" />
            <asp:Parameter DbType="Date" Name="end_date" />
            <asp:Parameter Name="offers_id" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>
    <br />
    <br />
    <asp:Button ID="Button1" runat="server" class="btn btn-success" Text="Add New Offer" />
    &nbsp;&nbsp;&nbsp;&nbsp;
    <asp:Button ID="Button3" runat="server" class="btn btn-success" Text="Add Offer On Product" />
    <div class="col-md-12">
        <div class="panel panel-success">
            <div class="panel panel-heading">
                Add Offer...</div>
            <asp:Panel ID="Panel1" runat="server" Visible="false">
                <div class="panel panel-body">
                    <table align="center">
                        <tr>
                            <td>
                                Offer Description :-
                            </td>
                            <td>
                                <asp:TextBox ID="offdesc" placeholder="Enter Offer Description..." runat="server"></asp:TextBox>
                            </td>
                            <td>
                                </td>
                        </tr>
                        <tr>
                            <td>
                                &nbsp
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Discount Rate(%) :-
                            </td>
                            <td>
                                <asp:TextBox ID="discount" placeholder="Enter Offer Discount..." runat="server" 
                                    TextMode="Number"></asp:TextBox>
                            </td>
                            <td>
                                  </td>
                        </tr>
                        <tr>
                            <td>
                                &nbsp
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Start Date :-
                            </td>
                            <td>
                                <asp:TextBox ID="Startdate" placeholder="Enter Offer Start Date..." 
                                    runat="server" TextMode="Date"></asp:TextBox>
                              
                            </td>
                            <td>
                                 </td>
                        </tr>
                        <tr>
                            <td>
                                &nbsp
                            </td>
                        </tr>
                        <tr>
                            <td>
                                End Date :-
                            </td>
                          
                            <td>
                                <asp:TextBox ID="Enddate" placeholder="Enter Offer End Date..." runat="server" 
                                    TextMode="Date"></asp:TextBox>
                            </td>
                            <td>
                                <asp:CompareValidator ID="CompareValidator1" runat="server" ErrorMessage="End Date is same or less then Start Date." Font-Bold="True" ForeColor="Red" Type="Date" Operator="LessThan" ControlToCompare="Enddate" ControlToValidate="Startdate"></asp:CompareValidator>
                                  </td>
                        </tr>
                        <tr>
                            <td>
                                &nbsp
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="panel panel-footer" align="center">
                    <asp:Button ID="Button2" runat="server" class="btn btn-success" Text="Add Offer" /></div>
            </asp:Panel>
            <asp:Panel ID="Panel2" runat="server" Visible="false">
                <table>
                    <tr>
                        <td>
                            Select Offer :-
                        </td>
                        <td>
                            <asp:DropDownList ID="DropDownList3" runat="server" DataSourceID="SqlDataSource3"
                                DataTextField="offer_desc" DataValueField="offers_id">
                            </asp:DropDownList>
                            <asp:SqlDataSource ID="SqlDataSource3" runat="server" 
                                ConnectionString="<%$ ConnectionStrings:OTSProjectConnectionString1 %>" 
                                SelectCommand="SELECT [offer_desc], [offers_id] FROM [Offer]">
                            </asp:SqlDataSource>
                        </td>
                        <td>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator6" runat="server" ErrorMessage="* Product is Required..."
                                ControlToValidate="DropDownList1" Font-Bold="True" ForeColor="Red"></asp:RequiredFieldValidator>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Select Product :-
                        </td>
                        <td>
                            <asp:DropDownList ID="DropDownList1" runat="server" DataSourceID="SqlDataSource2"
                                DataTextField="p_name" DataValueField="p_id">
                            </asp:DropDownList>
                            <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:OTSProjectConnectionString1 %>"
                                SelectCommand="SELECT [p_id], [p_name] FROM [Product]"></asp:SqlDataSource>
                        </td>
                        <td>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="* Product is Required..."
                                ControlToValidate="DropDownList1" Font-Bold="True" ForeColor="Red"></asp:RequiredFieldValidator>
                        </td>
                    </tr>
                </table>
                <asp:Button ID="Button4" runat="server" class="btn btn-success" Text="Add Offer On Product" />
        </div>
    </asp:Panel>
</asp:Content>
